### ISSUE TITLE
Unable to visualize html report in Azdo

### ISSUE THREAD

**Issue by GeekySurya** [lakshaykaushik/PublishHTMLReport#50]
Hi,
I am running jMeter test in my release pipeline using PowerShell script. Its generating jMeter reports scuccessfully.

 
![image](https://user-images.githubusercontent.com/50516247/131937482-7a12a093-3427-4db9-bd7f-ef8951d931d0.png)

Then I run publishhtmlreport task to publish reports to azdo.

The task completed successfully ..
![image](https://user-images.githubusercontent.com/50516247/131937587-602a62b1-3af9-4a96-b8f1-4c7f634988e9.png)

But I dont see any reports -

![image](https://user-images.githubusercontent.com/50516247/131937629-8f0664f6-6c34-42a3-a86f-b8ec92147c14.png)

Could you please let me know how can I visualize the report in azdo

Here is the yaml for my task 

steps:
- task: LakshayKaushik.PublishHTMLReports.publishhtmlreport.publishhtmlreport@1
  displayName: publishhtmlreport
  inputs:
    htmlType: Jmeter
    JmeterReportsPath: '$(System.DefaultWorkingDirectory)/_InteropService-dev-CD/jMeter/Output/reports'

**Comment by arunangshupodder** [comment]
Hi,
I am also facing similar issue. Can someone please suggest if we are missing out on any step.

**Comment by AErmie** [comment]
I'm also experiencing rendering issues with this extension. I have verified that the issue is with the extension itself.

I am running a JMeter test (via JMX file) in an Azure Pipeline...

**JMeter Azure Pipeline Script:**
```yaml
apache-jmeter-5.4.3/bin/./jmeter -Jjmeter.reportgenerator.overall_granularity=1000 \
  --nongui \
  --addprop "$(System.DefaultWorkingDirectory)/jmeter/MyTest.properties" \
  --testfile "$(System.DefaultWorkingDirectory)/jmeter/MyTest.jmx" \
  -JHost=$(HostName) \
  -JToken="${{ parameters.AuthToken }}" \
  --logfile results/results.jtl \
  --jmeterlogfile results/output.log \
  --reportatendofloadtests --reportoutputfolder report
```

When I capture the JMeter report output (like so)...

```yaml
- task: PublishPipelineArtifact@1
      displayName: 'Publish JMeter HTML Report'
      condition: succeededOrFailed()
      inputs:
        targetPath: report
        artifactName: JMeter-Report
        artifactType: pipeline
```

... and I look at the captured HTML file, it renders fully/properly. However, when I try to use this extension, the Published HTML tab in the pipeline is blank/empty.
