### ISSUE TITLE
Mochawesome HTML file doesn't load. Blank page is displayed

### ISSUE THREAD

**Issue by ZaidMomin1** [lakshaykaushik/PublishHTMLReport#53]
Hi,

I'm new to azure and trying to upload the mochawesome.html file in the azure pipeline.

As described here, https://github.com/lakshaykaushik/PublishHTMLReport, I have the set the below config with `htmltype: genericHTML`
```
steps:
- task: LakshayKaushik.PublishHTMLReports.publishhtmlreport.publishhtmlreport@1
  displayName: 'Publish HTML'
  inputs:
    htmlPath: '$(Build.Repository.LocalPath)/mochawesome-report/mochawesome.html'
  continueOnError: true
 ```
Image
![HtmlLoadingIssue](https://user-images.githubusercontent.com/17903154/146337148-331332fd-f2e0-4c5e-b4e3-699387edd194.PNG)

Your help would be highly appreciated.

Thanks,
Zaid
