### ISSUE TITLE
how to access published html report

### ISSUE THREAD

**Issue by anilsamuel** [lakshaykaushik/PublishHTMLReport#63]
I am using following definition; run shows success but unable to find the published report, please help
```
      - task: PublishHtmlReport@1
        displayName: 'Publish Search logs Output'
        inputs:
          htmlType: 'genericHTML'
          htmlPath: '$(Build.SourcesDirectory)/get-query-results.html'
```
